################################################
# Copyright 2019, Verizon Media.
# Licensed under the Apache License, Version 2.0
# See LICENSE file in project root for terms.
################################################

elide:
  modelPackage: 'example.models'
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
  async:
    enabled: true
    threadPoolSize: 2
    maxRunTime: 65
    cleanupEnabled: true
    queryCleanupDays: 7
    defaultAsyncQueryDAO: true
  aggregation-store:
    enabled: true
    default-dialect: h2
    enableMetaDataStore: false
  dynamic-config:
    path: src/main/resources/analytics
    enabled: true

spring:
  application:
    name: Elide
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.H2Dialect'
      ddl-auto: 'validate'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
    enabled: true
server:
  port: 8080
  tomcat:
    max-threads: 2

logging:
  path: /tmp

security:
  origin: "*"

---
elide:
  aggregation-store:
    default-dialect: Postgres

spring:
  profiles: production
  jpa:
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      ddl-auto: 'validate'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  liquibase:
    enabled: false
server:
  port: ${PORT}

security:
  origin: ${HOST}
